# Melting the Dataset

In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
dataframe = pd.read_csv("vgsales.csv")

## Shaping the Dataframe

For use in Tableau

In [25]:
dataframe

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [27]:
dataframemod = dataframe.drop_duplicates()
dataframemod.rename(columns={"NA_Sales": "North America", "EU_Sales": "Europe", "JP_Sales": "Japan", "Other_Sales" : "Other", "Global_Sales" : "Global"}, inplace=True)

sales_columns = ['North America','Europe','Japan', 'Global', 'Other']
melted_dataframe = pd.melt(dataframemod, id_vars=['Name', 'Year', 'Genre', 'Publisher', 'Platform'],
                           value_vars=sales_columns, var_name='Sales_Region', value_name='Sales')


melted_dataframe

,Name,Year,Genre,Publisher,Platform,Sales_Region,Sales
0,Wii Sports,2006.0,Sports,Nintendo,Wii,North America,41.49
1,Super Mario Bros.,1985.0,Platform,Nintendo,NES,North America,29.08
2,Mario Kart Wii,2008.0,Racing,Nintendo,Wii,North America,15.85
3,Wii Sports Resort,2009.0,Sports,Nintendo,Wii,North America,15.75
4,Pokemon Red/Pokemon Blue,1996.0,Role-Playing,Nintendo,GB,North America,11.27
...,...,...,...,...,...,...,...
82985,Woody Woodpecker in Crazy Castle 5,2002.0,Platform,Kemco,GBA,Other,0.00
82986,Men in Black II: Alien Escape,2003.0,Shooter,Infogrames,GC,Other,0.00
82987,SCORE International Baja 1000: The Official Game,2008.0,Racing,Activision,PS2,Other,0.00
82988,Know How 2,2010.0,Puzzle,7G//AMES,DS,Other,0.00
82989,Spirits & Spells,2003.0,Platform,Wanadoo,GBA,Other,0.00

## Adding Generations

In [28]:
def generation_def(year):
    if year <= 1989:
        return 'First Generation'
    elif 1989 < year <= 1994:
        return 'Second Generation'
    elif 1994 < year <= 2000:
        return 'Third Generation'
    elif 2000 < year <= 2005:
        return 'Fourth Generation'
    elif 2005 < year <= 2017:
        return 'Fifth Generation'
    else:
        return 'Fifth Generation'

# Creating the Column
melted_dataframe['Generation'] = melted_dataframe['Year'].apply(generation_def)

melted_dataframe

,Name,Year,Genre,Publisher,Platform,Sales_Region,Sales,Generation
0,Wii Sports,2006.0,Sports,Nintendo,Wii,North America,41.49,Fifth Generation
1,Super Mario Bros.,1985.0,Platform,Nintendo,NES,North America,29.08,First Generation
2,Mario Kart Wii,2008.0,Racing,Nintendo,Wii,North America,15.85,Fifth Generation
3,Wii Sports Resort,2009.0,Sports,Nintendo,Wii,North America,15.75,Fifth Generation
4,Pokemon Red/Pokemon Blue,1996.0,Role-Playing,Nintendo,GB,North America,11.27,Third Generation
...,...,...,...,...,...,...,...,...
82985,Woody Woodpecker in Crazy Castle 5,2002.0,Platform,Kemco,GBA,Other,0.00,Fourth Generation
82986,Men in Black II: Alien Escape,2003.0,Shooter,Infogrames,GC,Other,0.00,Fourth Generation
82987,SCORE International Baja 1000: The Official Game,2008.0,Racing,Activision,PS2,Other,0.00,Fifth Generation
82988,Know How 2,2010.0,Puzzle,7G//AMES,DS,Other,0.00,Fifth Generation
82989,Spirits & Spells,2003.0,Platform,Wanadoo,GBA,Other,0.00,Fourth Generation

## Exporting

In [29]:
melted_dataframe.to_csv('vgsalesmod.csv')

## To Do

Thursday
- Read Rubric
- Maps 
- Copy or Remake Charts

Friday
- Create a story
- Write Headlines